name: greetings

on:
    push:
        branches: [main]
jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Greeting Action
        id: greet
        uses: ./.github/actions/setup-and-greet
        with:
          name: 'Alfaiz'
          language: 'en'

      - name: Check Output
        run: echo "Greeted status:${{ steps.greet.outputs.greeted }}"
