# This is my first pipeline for project 90 days of devops
name: hello 

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploying Message
        run: echo "Hello from Github Actions!" 

      - name: date and timeout-minutes
        run: date +"%Y-%m-%d %H:%M:%S"

      - name: branch name
        run: echo "branch is ${{ github.ref_name }}"

  repo:
    runs-on: ubuntu-latest
    steps:
      - name: file in repo
        run: ls -R

  OS:
    runs-on: ubuntu-latest
    steps:
      - name: printing operating system
        run: echo "OS is ${{runner.os}}"

      - name: fail command
        run: mkdir day-40
        
