name: multiple jobs run

env:
    APP_NAME: myapp

on: 
    push:
        branches: [main]
        
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: staging
        steps: 
            - name: Print build
              run: echo "Building the app"

    test: 
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - env:
                VERSION: 1.0.0
              name: run test
              run: echo "Running tests"

    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: deploy app
              run: |
                echo "Deploying"
                echo "App Name: $APP_NAME"
                echo "Environment: $ENVIRONMENT"
                echo "Version: $VERSION"
                echo "Commit SHA  : ${{ github.sha }}"
                echo "Triggered By: ${{ github.actor }}"
