name: python app

on:
    workflow_dispatch:

jobs:
    my-app:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: app run
              run:
                pip install -r requirements.txt
                python app.py 

            - name: failed
              run: exit 1