name: python app

on:
    workflow_dispatch:

jobs:
    my-app:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: app run
              run: |
                pip install -r requirements.txt
                sudo apt-get update -y
                sudo apt-get install -y curl
                python app.py &
                sleep 3
                curl -f http://127.0.0

            - name: failed
              run: exit 1