name: secret add

on: 
    workflow_dispatch:

jobs: 
    print: 
        runs-on: ubuntu-latest
        steps: 
            - name: print secret
              run: |
                echo "My Secret is ${{secrets.MY_SECRET_MESSAGE}}"
                echo "The secret is set: True"

    secret-var:
        runs-on: ubuntu-latest
        steps:
            - name: secret as variable
              env:
                MY_SECRET: ${{secrets.MY_SECRET_MESSAGE}}
              run: echo "My secret is $MY_SECRET"