name: secret add

on: 
    workflow_dispatch:

jobs: 
    print: 
        runs-on: ubuntu-latest
        steps: 
            - name: print secret
              run: |
                echo "My Secret is ${{secrets.MY_SECRET_MESSAGE}}"
                echo "The secret is set: True"