name: smart triggers

#on:
# push:
#   paths:
#     - 'src/**'
#     - 'app/**'

on:
  push:
    paths-ignore:
            - '*.md'
            - 'docs/**'
jobs: 
    smart-triggers:
        runs-on: ubuntu-latest
        steps: 
            - name: Triggers
              run: ls