name: trigger on push

on:
    push:

jobs:
    lint-job:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install Linting Tools
              run: |
                pip install -r requirements.txt
                ruff check app.py

    test-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                python -m pytest app.py

    summary:
        runs-on: ubuntu-latest
        steps:
            - name: Identify Branch Push Type
              run: |
                if [ "${{ github.ref_name }}" = "main" ]; then
                  echo "This is a main branch push! Ready for production deployment."
                else
                  echo "This is a feature branch push! Running tests on branch: ${{ github.ref_name }}"
                fi
                echo "commit message: ${{ github.event.commits[0].message }}"