name: smart triggers

on:
  push:
    paths:
      - 'src/**'
      - 'app/**'

jobs: 
    smart-triggers:
        runs-on: ubuntu-latest
        steps: 
            - name: Triggers
              run: ls